### ISSUE TITLE
Navigation (MVP)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#1]
## Value statement
As a **customer** 
I need a **navigation** 
so that I know **where I am** and **where I need to go next** 
## Description (Text, Scribble, Wireframe, Design)
![Home](https://user-images.githubusercontent.com/72032645/99881289-24509f00-2c19-11eb-84d6-ef353466831e.png)

## Acceptance criteria
- [x] Header and Footer are build in and (almost) consistently present
## Tasks
- [x] Initiate react app
- [x] setting up routing
- [x] creating components
- [x] assign paths and links
## Size
medium
