### ISSUE TITLE
Checkout (Bonus)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#10]
## Value statement - a requirement, not a solution
As a **customer** 
I need **to checkout** 
so that **my order is proceeded** 
## Description (Text, Scribble, Wireframe, Design)
![Shipping   Payment](https://user-images.githubusercontent.com/72032645/99882856-a5ad2f00-2c23-11eb-9f42-7d20aa33fa81.png)
![Summary](https://user-images.githubusercontent.com/72032645/99882858-a8a81f80-2c23-11eb-9292-c941b0277af1.png)
![Sign In (checkout) – 1](https://user-images.githubusercontent.com/72032645/99882906-050b3f00-2c24-11eb-97fd-427c0c06d9d0.png)

## Acceptance criteria
- [x] Personal data loaded when logged in
- [x] Payment options can be selected from
- [x] Confirmation shown when order is proceeded

## Tasks
- [x] Push data into state in order to post information
- [x] Create order form component
- [x] Set values if logIn === true
- [x] Create summary with edit function

## Size
large
