### ISSUE TITLE
Whisky Finder (Bonus)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#11]
## Value statement - a requirement, not a solution
As a **customer** 
I appreciate **a costum product recommendation** 
so that **I buy the most suitable product** 
## Description (Text, Scribble, Wireframe, Design)
![Home – 1](https://user-images.githubusercontent.com/72032645/99883007-b5794300-2c24-11eb-805a-8a65e7e913c4.png)

## Acceptance criteria
- [ ] Preset filter based on 3-4 answers provided
## Tasks
- [ ] Set up form with 3-4 questions
- [ ] Set State with all product data
- [ ] Create buttons with filter functionality
- [ ] Update State onclick to narrow down the selection

## Size
large
