### ISSUE TITLE
Product Review (Bonus)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#12]
## Value statement - a requirement, not a solution
As a **user** 
I would like **see product reviews / rate products** 
so that **I can separate good from bad quality products** 

## Acceptance criteria
- [ ] See product reviews in overview and on detail page
- [ ] Being able to rate when logged in

## Tasks
- [ ] check user loggin === true
- [ ] implement radion button rating and styling
- [ ] implement rating data in product data (backend)
- [ ] calculate average 
- [ ] set post route

## Size
medium
