### ISSUE TITLE
Bookmark (MVP)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#3]
## Value statement - a requirement, not a solution
As a **custumer** 
I want to **bookmark** my favorite items
so that **can reconsider them** at any time during the process
## Description (Text, Scribble, Wireframe, Design)
![Favorites](https://user-images.githubusercontent.com/72032645/99881431-2404d380-2c1a-11eb-8af0-4fa95460e06e.png)

## Acceptance criteria
- [x] They are added on click to my list
- [x] The list is accessable through the navigation
- [x] The list highlighted how many are marked as favorite
## Tasks
- [x] Add bookmark toggle to database (boolean)
- [x] Add counter function to list
- [x] Link counter to navigation component
- [x] Pass callback function to component
- [x] Implement remove and buy buttons

## Size
medium
