### ISSUE TITLE
SignIn / SignOut / SignUp (Bonus)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#4]
## Value statement - a requirement, not a solution
As a **customer** 
I want to **login/out or sign up** 
so that **I my personal data is loaded automatically** 
## Description (Text, Scribble, Wireframe, Design)
![Sign In (checkout)](https://user-images.githubusercontent.com/72032645/99881663-4e0ac580-2c1b-11eb-93dc-b0dd6276c369.png) ![Sign In (checkout)](https://user-images.githubusercontent.com/72032645/99881667-519e4c80-2c1b-11eb-9225-a9b3cbfca86d.png) ![Sign Up](https://user-images.githubusercontent.com/72032645/99881669-55ca6a00-2c1b-11eb-9269-3da24917823e.png) 

## Acceptance criteria
- [ ] I can access the logIn/logOut function at any time via the menu
- [ ] However, I can also buy as a visitor if I would like to
- [ ] When logged in, my shipping/billing data is loaded automatically
## Tasks
- [ ] Initiate user entity in backend
- [ ] Set post route to send login data
- [ ] Implement user authentification (temporary auth-key)
- [ ] Create sign up form component
- [ ] Create sign in form component

## Size
large
