### ISSUE TITLE
Menu (MVP)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#5]
## Value statement - a requirement, not a solution
As a **customer** 
I need **access many functionalities**  anywhere during the process
so that **I have full control over the buying process** 

## Description (Text, Scribble, Wireframe, Design)
![Menu (logged out)](https://user-images.githubusercontent.com/72032645/99882380-4568be00-2c20-11eb-9e01-c0b58f166683.png)
![Menu (logged in)](https://user-images.githubusercontent.com/72032645/99882377-41d53700-2c20-11eb-80a2-99997b984fc9.png)

## Acceptance criteria
- [ ] Functioning menu button in navigation
## Tasks
- [ ] Include LogIn / LogOut button depending on current State
- [ ] Show / Hide past order button and include bookmarks
- [ ] Include different categories (preset filters)
- [ ] Create styled overlay

## Size
medium
