### ISSUE TITLE
Filter / Sort button (MVP)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#6]
## Value statement - a requirement, not a solution
As a **customer** 
I need **to filter** 
so that **find suitable products quickly** 
## Description (Text, Scribble, Wireframe, Design)
![Product Overview ( with filter)](https://user-images.githubusercontent.com/72032645/99882447-db9ce400-2c20-11eb-8204-4f115e172d7a.png)
![Filter](https://user-images.githubusercontent.com/72032645/99882454-e5264c00-2c20-11eb-9831-57d86cf5ed5b.png)
![Product Overview](https://user-images.githubusercontent.com/72032645/99882456-e9526980-2c20-11eb-8965-545c3d0454f4.png)

## Acceptance criteria
- [x] Working filter overlay on click
- [x] Working sort button
## Tasks
- [x] Write functions for different filter tasks
- [x] Implement filter componenents
- [x] Implement new state (array) to push filtered items into
- [x] Implement reset button

## Size
large
