### ISSUE TITLE
Frontend + Backend - Technical Basics (MVP)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#7]
## Value statement - a requirement, not a solution
As a **customer** 
I need **to access the current product data** 
so that **I can always take advantage of the cheapest offer** 

## Acceptance criteria
- [x] I can see and compare multiple product offers 
## Tasks
- [x] Install and set up backend + frontend server (react/php/symfony)
- [x] Set product entity (MVP)
````
{
  ("id");
  **("gtin");** -> link to "offers"
  ("title");
  ("brand");
  ("image");
  ("description");
  ("size");
  ("volume");
  ("origin");
  **("taste");** -> WhiskyFinder (optional)
  **("category");** -> WhiskyFinder (optional)
  **("genre");** -> WhiskyFinder (optional)
  **("level");** -> WhiskyFinder (optional)
}
````
- [x] Set offers entity (MVP)
````
{
  ("id");
  **("gtin");** -> link to "product"
  ("price");
  ("shipping");
  ("delivery");
  ("seller");
  ("onStock");
}
````
- [x] Set default data
- [x] Set post and get routes for accessability by frontend
````
## Size
large
