### ISSUE TITLE
Product Page / Product Detail Page (MVP)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#8]
## Value statement - a requirement, not a solution
As a **customer** 
I need **see have information of available products** 
so that **can take a decision to buy or not** 
## Description (Text, Scribble, Wireframe, Design)
![Product Detail Page](https://user-images.githubusercontent.com/72032645/99882680-98dc0b80-2c22-11eb-873f-b4fa1d980ef0.png)
![Product Overview](https://user-images.githubusercontent.com/72032645/99882677-95488480-2c22-11eb-8d2c-6ef596f7845e.png)

## Acceptance criteria
- [x] Product details page opens when clicking on item
- [x] Basic information is visible on product overview
## Tasks
- [x] Create product details component
- [x] Fetch necessary data by default from server
- [x] Select cheapest offer by default
- [x] Implement option to choose different source (id)
- [x] Implement toggle button for show/hide suppliers

## Size
medium
