### ISSUE TITLE
Card (MVP)

### ISSUE THREAD

**Issue by marrep** [marrep/capstone#9]
## Value statement - a requirement, not a solution
As a **customer** 
I need **to add items to my card** 
so that **I can see a selection of my products** 
## Description (Text, Scribble, Wireframe, Design)
![Shopping Cart](https://user-images.githubusercontent.com/72032645/99882767-418a6b00-2c23-11eb-9dfc-d2ba6d0345a1.png)

## Acceptance criteria
- [x] Seeing selected products when clicking on card
- [x] Current amount of items visible in navigation
## Tasks
- [x] Add state with card products
- [x] Push products into array on click
- [x] Counting current amount of products in state

## Size
medium
